### PR TITLE
refactor : export response function outside

### PR DESCRIPTION
**Pull request by YunYeongChang**
codes were refactored - step A

### CODE REVIEW

**Comment by YunYeongChang** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
           

Complexity increasing per file
==============================
- routes/coms/jwtToken.js  3
         

Complexity decreasing per file
==============================
+ routes/auth/pwdreset/pwdsend.js  -2
+ routes/auth/login.js  -1
+ routes/auth/pwdchange.js  -1
+ routes/auth/signup.js  -2
+ routes/auth/pwdreset/pwdreset.js  -1
+ routes/auth/social_kakao.js  -3
         

Clones removed
==============
+ routes/auth/pwdreset/pwdsend.js  -6
+ routes/auth/login.js  -2
+ routes/auth/pwdchange.js  -3
+ routes/auth/signup.js  -9
+ routes/auth/pwdreset/pwdreset.js  -5
+ routes/auth/social_kakao.js  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/readlight/readlight-backend/pullRequest?prid=6138287&bid=20069353)

**Comment by YunYeongChang** [comment]
@wkdwhddn06 @plantstoen @xodus0721 
그냥 Approve 부탁드립니다.

**Review by YunYeongChang — COMMENTED** [review]
Approve Merge Required

**Review by xodus0721 — APPROVED** [review]

**Review by wkdwhddn06 — APPROVED** [review]

**Comment by YunYeongChang** [comment]
ERROR: THIS PR HAVE NOT MERGED INTO MASTER.
REASON: NO SIGNED COMMITS LOADED.

**Comment by YunYeongChang** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- routes/coms/jwtToken.js  3
         

Clones added
============
- routes/auth/pwdchange.js  7
- routes/auth/login.js  10
- routes/auth/pwdreset/pwdsend.js  2
- routes/auth/pwdreset/pwdreset.js  6
- routes/auth/social_kakao.js  3
- routes/auth/signup.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/readlight/readlight-backend/pullRequest?prid=6138287&bid=20069353)

**Pull request merged**
